### ISSUE TITLE
Support input unions

### ISSUE THREAD

**Issue by jasonkuhrt** [jasonkuhrt/molt#107]
#### Perceived Problem

User wants an interface like this:

```
Case 1:
foo 

Case 2:
foo -i

Case 3:
foo -i yarn
foo -I npm
foo -i pnpm
```

Case 1, when nothing given, means, don't do `-i` thing.
Case 2, when given as boolean, means, do `-i` thing with some default behaviour
case 3, when given, means, do `-i` thing with this

#### Ideas / Proposed Solution(s)

How could this be represented in the Zod types?

```ts
z.boolean().or(z.enum(['a','b','c'])).default(false)
```

Should do it.

The internal type would be:

```
true | false | 'a' | 'b' | 'c'
```

The `false` case is because 1) its the default and 2) the user could do this explicitly:

```
foo --no-i
```

Currently Mold Command does not know how to parse based on an input union. Nor does it know how to generate docs for an input union.

For parsing there are few rules:

1. If the union includes string literals AND a boolean those string literals CANNOT be `false` or `true` since that would make it impossible to properly parse/cast the environment input.

2. Looking at the above example for a concrete example: When parsing the flags, we assume that this `-i --something-else` means the user is intending to pass as the boolean union member. When they pass `-i yarn --something-else` we assume the enum.

3. This kind of zod expression would be unsupportable by Molt: `z.boolean().or(z.enum(['a','b','c']).default('b')).default(false)`. A default on a member within the union is not parsable.

~The above leads me to believe that we shouldn't support zod unions but instead roll our own, like we did with `.mutuallyExclusive`. We could have `.union` or `.or` or even simpler could just be accepting an array as the second parameter to `.parameter`:~

Ignore examples below and see comment below.

```ts
Command.parameter('i install', [z.boolean(), z.enum(['a','b','c'])])
```

Ah, but the problem with this is we lose the ability to express the concept of a default for the parameter. Ok, try again with a builder function then:

```ts
Command
  .parameter('i install', __ =>
    __.value(z.enum(['a','b','c']).description('...'))
      .value(z.boolean().description('...'))
      .default(true)
  )
```

**Comment by jasonkuhrt** [comment]
Maybe the approach of supporting zod unions is actually best...

Its just that we need to have some limits:

1. No defaults on inner union members (only ok top level)
2. No optionals on inner union members (only ok top level)

Then we can support this:

```ts
Command
  .parameter('i install', z.boolean().or(z.enum(['a','b','c'])).default(false))
```

**Comment by jasonkuhrt** [comment]
How should the help be rendered for this? Example of some current docs:

<img width="953" alt="CleanShot 2022-12-18 at 09 13 40@2x" src="https://user-images.githubusercontent.com/284476/208303210-1eae3105-cd8b-4134-a45f-3f8b95f40ce9.png">


Here is an example sketch where we just stack the type/description cell with additional entries for each union member. This sketch assumes descriptions have been given for each member:

```
PARAMETERS

  Name       Type/Description                              Default      
  
  move       boolean                                       false        
  m          Delete the original file after it has be                              
             en converted.                                                         
  
  install    boolean                                       false        
  i          Run dependency install after setup. Use
             the system-detected package manager.                           
  
             yarn | pnpm | npm                                       
             Force use of a specific package manager.                                                  
  
  filePath   string                                         REQUIRED    
             Path to the file to convert.                                          
  
  from       json | yaml | toml                            undefined    
             Format to convert from. By default infer                              
             red from the file extension.                                            
```

Here's the sketch where no descriptions were given:

```
PARAMETERS

  Name       Type/Description                              Default      
  
  move       boolean                                       false        
  m          Delete the original file after it has be                              
             en converted.                                                         
  
  install    boolean | yarn | pnpm | npm                   false        
  i                                                      
  
  filePath   string                                         REQUIRED    
             Path to the file to convert.                                          
  
  from       json | yaml | toml                            undefined    
             Format to convert from. By default infer                              
             red from the file extension.                                            
```

Here is an example where description was given at the union and member levels:

```
PARAMETERS

  Name       Type/Description                              Default      
  
  move       boolean                                       false        
  m          Delete the original file after it has be                              
             en converted.                                                         
  
  install    union                                         false        
  i          Run dependency install after setup.                           

             boolean
             Use the system-detected package manager.
  
             yarn | pnpm | npm                                       
             Force use of a specific package manager.                                                  

  filePath   string                                         REQUIRED    
             Path to the file to convert.                                          
  
  from       json | yaml | toml                            undefined    
             Format to convert from. By default infer                              
             red from the file extension.                                            
```

**Comment by jasonkuhrt** [comment]
Maybe we can take some inspiration from how mutually exclusive parameters are rendered:

<img width="809" alt="CleanShot 2022-12-18 at 09 24 27@2x" src="https://user-images.githubusercontent.com/284476/208303657-831635ef-b7dc-4890-b655-9dcc9d6edfd5.png">


Idea:

```
PARAMETERS

  Name       Type/Description                              Default      
  
  move       boolean                                       false        
  m          Delete the original file after it has be                              
             en converted.                                                         
  
  install    ┌─union                                       false        
  I          │ Run dependency install after setup.                           
             │
             ◒ boolean
             │ Use the system-detected package manager.
             │
             ◒ yarn | pnpm | npm                                       
             │Force use of a specific package manager.                                                  
             └─
  filePath   string                                         REQUIRED    
             Path to the file to convert.                                          
  
  from       json | yaml | toml                            undefined    
             Format to convert from. By default infer                              
             red from the file extension.
```

**Comment by sabinadams** [comment]
> Maybe we can take some inspiration from how mutually exclusive parameters are rendered:
> 
> <img alt="CleanShot 2022-12-18 at 09 24 27@2x" width="809" src="https://user-images.githubusercontent.com/284476/208303657-831635ef-b7dc-4890-b655-9dcc9d6edfd5.png">
> 
> Idea:
> 
> ```
> PARAMETERS
> 
>   Name       Type/Description                              Default      
>   
>   move       boolean                                       false        
>   m          Delete the original file after it has be                              
>              en converted.                                                         
>   
>   install    ┌─union                                       false        
>   i          │ Run dependency install after setup.                           
>              │
>              ◒ boolean
>              │ Use the system-detected package manager.
>              │
>              ◒ yarn | pnpm | npm                                       
>              │ Force use of a specific package manager.                                                  
>              └─
>   
>   filePath   string                                         REQUIRED    
>              Path to the file to convert.                                          
>   
>   from       json | yaml | toml                            undefined    
>              Format to convert from. By default infer                              
>              red from the file extension.
> ```

I really like this approach. To me, it makes it the most clear that there are multiple potential input types and the scenarios each covers.

**Comment by jasonkuhrt** [comment]
I wonder if we should render it that way even when no descriptions are given. My thinking is that if you're not giving descriptions you probably don't care about the expanded rendering.

**Comment by jasonkuhrt** [comment]
Made some more progress tonight, this time on help rendering. Here's how its looking:

<img width="1178" alt="CleanShot 2022-12-27 at 21 21 17@2x" src="https://user-images.githubusercontent.com/284476/209747220-39da2046-182d-46ce-8660-0542dde0c196.png">

Its not perfect but I think this iteration of work has been long enough, its got value now, could ship.
